### ISSUE TITLE
[BUG] 알림 주기 변경을 했을 때 request 생성이 안되는 문제

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#139]
# 🐞 버그 설명
코드를 정확히 이해했는지 모르겠지만,  알림 주기에 변경이 생겼을 때 코드상 pending request 모두를 지우는 코드는 있지만, 변경된 주기를 기반으로 새로운 request를 만드는 부분이 생략된 것 같습니다.
나중에 버그 개선할 때 작성하면 늦을 것 같아 미리 작성했습니다
확인 부탁드려요 ~ @Gobans

**Comment by Gobans** [comment]
이미했어 ㅅㄱ
